#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${SQL_DATABASE}",
        user="${SQL_USER}",
        password="${SQL_PASSWORD}",
        host="${SQL_HOST}",
        port="${SQL_PORT}",
    )

except psycopg2.OperationalError:
    sys.exit(-1)

sys.exit(0)

END
}
until postgres_ready; do
    >&2 echo "Waiting for Postgres to be ready..."
    sleep 1
done
>&2 echo "Postgres is up - continuing..."

exec "$@"